Fixed short-circuit evaluation from brightness bound overrides.
acidanthera/WhateverGreen pull request #119
Opened 2024-07-18 09:56 UTC by damiponce

Currently, if both `backlight-smoother-lowerbound` and `backlight-smoother-upperbound` are set, the upper bound will be ignored due to the OR evaluation in [this](https://github.com/acidanthera/WhateverGreen/blob/21c7ffb6fda24443b22fc5d9cfc6b2cdbfb3c542/WhateverGreen/kern_igfx_backlight.cpp#L1358C2-L1359C103) `if` statement.

Changed the _logical_ OR to a _bitwise_ OR to force both bound checks.

2024-07-18 19:26 UTC, 0xFireWolf requested changes
Thanks for catching this stupid bug I made. However, for better readability, I suggest separating it into two `if` statements.

```c++
if (WIOKit::getOSDataValue(info->videoBuiltin, "backlight-smoother-lowerbound", brightnessRange.first))
	DBGLOG("igfx", "BLS: User requested brightness lower bound = %u.", brightnessRange.first);
if (WIOKit::getOSDataValue(info->videoBuiltin, "backlight-smoother-upperbound", brightnessRange.second))
	DBGLOG("igfx", "BLS: User requested brightness upper bound = %u.", brightnessRange.second);
```

2024-07-18 21:23 UTC, 0xFireWolf approved these changes

2024-07-18 21:25 UTC, damiponce commented
Fair enough on the formatting! I have to give credit to [Gwy](https://discord.com/channels/186648463541272576/349988041797926913/1263318615856381983) over on the Hackintosh Discord.

2024-07-22 02:24 UTC, merged

2024-07-22 02:24 UTC, vit9696 commented
Thank you!